# Generated by Django 5.1.6 on 2025-03-06 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ams_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='face_encoding',
            field=models.TextField(blank=True, default='[]'),
        ),
    ]
