# Generated by Django 5.1.6 on 2025-03-08 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ams_app', '0002_alter_students_face_encoding'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='face_encoding',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
