# Generated by Django 5.1.6 on 2025-04-04 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ams_app', '0003_alter_students_face_encoding'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScannedRFID',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=100)),
                ('scanned_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
