# Generated by Django 5.1.6 on 2025-04-04 23:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ams_app', '0004_scannedrfid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scannedrfid',
            name='scanned_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='scannedrfid',
            name='tag',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
