# Generated by Django 5.1.6 on 2025-04-13 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ams_app', '0005_alter_scannedrfid_scanned_at_alter_scannedrfid_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancereport',
            name='marked_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
