# Generated by Django 5.1.6 on 2025-04-14 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ams_app', '0006_attendancereport_marked_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scannedrfid',
            name='scanned_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='scannedrfid',
            name='tag',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
