# Generated by Django 5.1.6 on 2025-04-14 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ams_app', '0007_alter_scannedrfid_scanned_at_alter_scannedrfid_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scannedrfid',
            name='tag',
            field=models.CharField(max_length=100),
        ),
    ]
