# Generated by Django 5.1.6 on 2025-06-03 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ams_app', '0008_alter_scannedrfid_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffs',
            name='face_encoding',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='staffs',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/'),
        ),
    ]
