# Generated by Django 5.1.6 on 2025-06-06 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ams_app', '0010_alter_attendancereport_status_staffattendance_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='enrollment',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='sections',
            name='section_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='students',
            name='id_number',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='subjects',
            name='subject_code',
            field=models.CharField(max_length=255),
        ),
    ]
